FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .

RUN pip install -r requirements.txt

# Install Chromium for headless browsing
RUN playwright install --force chromium
COPY main.py .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
