apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: podlands-backend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: podlands-backend
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: podlands-frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: podlands-frontend
  policy:
    alphabetical:
      order: asc